import { describe, expect, it } from "vitest";
import { runTokenMetering, estimateTokenMetering } from "./run";
import { renderTokenMeteringReport } from "./domain/report";
import { articleOutlineProblems } from "../research/domain/article-outline";
import { TOKEN_SAMPLES } from "./samples";
import { FAMILY_CARDS } from "./models";

describe("sample manifest tm-v1", () => {
  it("holds 30 unique samples, 10 per class, split 5 calibration / 5 holdout", () => {
    expect(TOKEN_SAMPLES.length).toBe(30);
    expect(new Set(TOKEN_SAMPLES.map((sample) => sample.id)).size).toBe(30);
    for (const sampleClass of ["english", "japanese", "code"] as const) {
      const ofClass = TOKEN_SAMPLES.filter(
        (sample) => sample.class === sampleClass,
      );
      expect(ofClass.length).toBe(10);
      expect(
        ofClass.filter((sample) => sample.role === "calibration").length,
      ).toBe(5);
      expect(ofClass.every((sample) => sample.text.length > 0)).toBe(true);
    }
  });
});

describe("runTokenMetering (fixture)", () => {
  it("measures all four families deterministically at zero spend", async () => {
    const first = await runTokenMetering({ fixture: true });
    const second = await runTokenMetering({ fixture: true });
    expect(JSON.stringify(first)).toBe(JSON.stringify(second));
    expect(first.families.length).toBe(FAMILY_CARDS.length);
    expect(first.spendUsd).toBe(0);
    expect(first.generatedAt).toBe("2026-01-01T00:00:00.000Z");
    for (const family of first.families) {
      expect(family.provenance).toBe("fixtured");
      expect(family.rows.length).toBe(TOKEN_SAMPLES.length);
      // The fixture ground truth is generated by the same affine model the
      // calibration fits, so the harness must recover it near-exactly.
      expect(family.holdoutMaxAbsErrorPct ?? 100).toBeLessThanOrEqual(5);
    }
  });

  it("records an exact self content count for the exact-BPE families only", async () => {
    const result = await runTokenMetering({ fixture: true });
    for (const family of result.families) {
      const hasSelfCounts = family.rows.every(
        (row) => row.selfContentTokens !== undefined,
      );
      expect(hasSelfCounts).toBe(family.card.countingMethod === "exact-bpe");
    }
  });

  it("records unreachable rows instead of faking counts without a probe", async () => {
    const result = await runTokenMetering({
      fixture: false,
      probeFactory: () => undefined,
    });
    for (const family of result.families) {
      expect(family.provenance).toBe("unreachable");
      expect(family.rows.length).toBe(0);
    }
  });

  it("records error rows honestly when a probe throws", async () => {
    const result = await runTokenMetering({
      fixture: false,
      probeFactory: () => () => Promise.reject(new Error("boom")),
      familyIds: ["anthropic-claude"],
    });
    const family = result.families[0];
    expect(family?.provenance).toBe("error");
    expect(family?.rows.every((row) => row.provenance === "error")).toBe(true);
    expect(family?.rows.every((row) => row.apiTokens === undefined)).toBe(true);
  });
});

describe("renderTokenMeteringReport", () => {
  it("conforms to the standard 7-section English outline", async () => {
    const result = await runTokenMetering({ fixture: true });
    const markdown = renderTokenMeteringReport(result);
    expect(articleOutlineProblems(markdown, "english")).toEqual([]);
  });

  it("keeps section 4 inside the published-page budget", async () => {
    const result = await runTokenMetering({ fixture: true });
    const markdown = renderTokenMeteringReport(result);
    const section4 = markdown.split("## 4. Verification Results")[1] ?? "";
    const body = section4.split("## 5.")[0] ?? "";
    expect(body.replace(/<svg[\s\S]*?<\/svg>/g, "").length).toBeLessThanOrEqual(
      3000,
    );
  });
});

describe("estimateTokenMetering", () => {
  it("prices only the usage-probe families and stays inside the ceiling", () => {
    const estimate = estimateTokenMetering();
    expect(estimate).toContain("unbilled ($0)");
    expect(estimate).toContain("approx benchmark API cost");
    const match = estimate.match(/approx benchmark API cost: ~\$([\d.]+)/);
    expect(Number(match?.[1])).toBeLessThan(1);
  });
});
