import type { OcrComparisonResult, OcrModelRun } from "./types";
import { providerDisplayName } from "../../llm-model-comparison/domain/provider";

const pct = (value: number): string => `${(value * 100).toFixed(1)}%`;

const metric = (run: OcrModelRun, key: keyof OcrModelRun["stats"]): string => {
  const stat = run.stats[key];
  return stat.n === 0
    ? "未測定"
    : `${pct(stat.mean)} ± ${(stat.stdDev * 100).toFixed(1)}pp (n=${stat.n})`;
};

const sentence = (value: string): string =>
  value.endsWith(".") ? value : `${value}.`;

const resultRows = (result: OcrComparisonResult): string =>
  result.runs
    .map(
      (run) =>
        `| ${run.modelName} | ${providerDisplayName(run.provider)} | ${run.provenance} | ` +
        `${run.measuredAt} | ` +
        `${metric(run, "characterErrorRate")} | ${metric(run, "wordErrorRate")} | ` +
        `${metric(run, "fieldAccuracy")} | ${run.error ?? ""} |`,
    )
    .join("\n");

const documentRows = (result: OcrComparisonResult): string =>
  result.dataset.documents
    .map(
      (document) =>
        `| ${document.id} | ${document.license} | ${document.referenceText.length} | ` +
        `${Object.keys(document.fields).join(", ")} |`,
    )
    .join("\n");

const renderedImageRows = (result: OcrComparisonResult): string =>
  result.dataset.documents
    .map((document) => {
      const call = result.runs
        .flatMap((run) => run.calls)
        .find((record) => record.documentId === document.id);
      return `| ${document.id} | ${call ? "rendered during fixture run" : "not rendered in out-of-scope rows"} |`;
    })
    .join("\n");

export const renderOcrComparisonReport = (
  result: OcrComparisonResult,
): string => `---
title: OCR comparison
description: Reproducible OCR capability harness for vision-capable foundation models, using deterministic document images and CER/WER/field-level scoring.
---

# OCR comparison

This report records the OCR comparison harness for LLM foundation research. The committed report is generated by the keyless fixture path. Real model numbers are not present unless provenance is \`measured\`.

## Methodology

**Dataset.** ${result.dataset.dataset.name} (\`${result.dataset.dataset.id}\`), manifest version ${result.dataset.dataset.manifestVersion}. Source: ${result.dataset.dataset.source}. License: ${sentence(result.dataset.dataset.license)} ${sentence(result.dataset.dataset.imageDistribution)}

**Preprocessing.** Images are rendered as ${result.dataset.preprocessing.mimeType} at ${result.dataset.preprocessing.resolution.widthPx}×${result.dataset.preprocessing.resolution.heightPx}px, ${result.dataset.preprocessing.resolution.dpi} DPI. ${result.dataset.preprocessing.pageSplitting} ${result.dataset.preprocessing.rendering}

**Language and layout.** ${result.dataset.preprocessing.languageScript} ${result.dataset.preprocessing.layoutDifficulty}

**Scoring.** ${sentence(result.dataset.normalization.scoring)} Normalization: ${sentence(result.dataset.normalization.whitespace)} ${sentence(result.dataset.normalization.punctuation)}

**Structured schema.** Required fields: ${result.dataset.schema.fields.map((field) => `\`${field.name}\``).join(", ")}.

## Results

| Model | Provider | Provenance | Measured at | CER | WER | Field accuracy | Note |
| ----- | -------- | ---------- | ----------- | --- | --- | -------------- | ---- |
${resultRows(result)}

## Manifest sample

| Document id | License | Reference characters | Structured fields |
| ----------- | ------- | -------------------- | ----------------- |
${documentRows(result)}

## Rendered image provenance

| Document id | Image provenance |
| ----------- | ---------------- |
${renderedImageRows(result)}

## Scope and limitations

- Fixture rows are harness checks only. They prove that document rendering, vision-port wiring, CER/WER, field scoring, aggregation, and report rendering are deterministic.
- Rows marked \`out-of-scope\` are not sent through the image path. A provider/model needs an explicit \`VisionClient\` adapter before it can enter the OCR run.
- Real model numbers remain 未測定 until an owner runs the real path after reviewing \`--estimate\`.
- The synthetic fixture covers clean Latin/digit document layouts only. It does not measure Japanese OCR, handwriting, skew, stamps, scans, photos, or multi-page splitting.

## Reproduce

\`\`\`sh
cd packages/tech
npm install

# Keyless byte-stable fixture:
npm run ocr:fixture

# Estimate before any real vision run:
npm run ocr:estimate

# Owner-gated real path:
npm run ocr:real
\`\`\`

Generated: ${result.generatedAt}
`;
