import type { OcrComparisonResult, OcrModelRun } from "./types";
import { providerDisplayName } from "../../llm-model-comparison/domain/provider";
import { renderEnglishResearchArticle } from "../../research/domain/article-outline";

const pct = (value: number): string => `${(value * 100).toFixed(1)}%`;

const metric = (run: OcrModelRun, key: keyof OcrModelRun["stats"]): string => {
  const stat = run.stats[key];
  return stat.n === 0
    ? "not measured"
    : `${pct(stat.mean)} ± ${(stat.stdDev * 100).toFixed(1)}pp (n=${stat.n})`;
};

const sentence = (value: string): string =>
  value.endsWith(".") ? value : `${value}.`;

const resultRows = (result: OcrComparisonResult): string =>
  result.runs
    .map(
      (run) =>
        `| ${run.modelName} | ${providerDisplayName(run.provider)} | ${run.provenance} | ` +
        `${run.measuredAt} | ` +
        `${metric(run, "characterErrorRate")} | ${metric(run, "wordErrorRate")} | ` +
        `${metric(run, "fieldAccuracy")} | ${run.error ?? ""} |`,
    )
    .join("\n");

const documentRows = (result: OcrComparisonResult): string =>
  result.dataset.documents
    .map(
      (document) =>
        `| ${document.id} | ${document.license} | ${document.referenceText.length} | ` +
        `${Object.keys(document.fields).join(", ")} |`,
    )
    .join("\n");

const renderedImageRows = (result: OcrComparisonResult): string =>
  result.dataset.documents
    .map((document) => {
      const call = result.runs
        .flatMap((run) => run.calls)
        .find((record) => record.documentId === document.id);
      return `| ${document.id} | ${call ? "rendered during fixture run" : "not rendered in out-of-scope rows"} |`;
    })
    .join("\n");

export const renderOcrComparisonReport = (
  result: OcrComparisonResult,
): string =>
  renderEnglishResearchArticle({
    title: "OCR comparison",
    description:
      "Reproducible OCR capability harness for vision-capable foundation models, using deterministic document images and CER/WER/field-level scoring.",
    introduction:
      "This report records the OCR comparison harness for LLM foundation research. The committed report is generated by the keyless fixture path.",
    purpose:
      "The purpose is to verify which foundation-model integrations can perform OCR over deterministic document images and return both transcription text and structured fields.",
    targetModels:
      "The target rows are the model candidates in the OCR runner. Real model numbers are present only when a row's provenance is `measured`; `out-of-scope` rows identify models without a registered `VisionClient` adapter.",
    targetMetrics: `The measured metrics are character error rate (CER), word error rate (WER), and field-level structured extraction accuracy. Required fields: ${result.dataset.schema.fields.map((field) => `\`${field.name}\``).join(", ")}.`,
    scopeAndConstraints: `- Fixture rows are harness checks only. They prove that document rendering, vision-port wiring, CER/WER, field scoring, aggregation, and report rendering are deterministic.
- Rows marked \`out-of-scope\` are not sent through the image path. A provider/model needs an explicit \`VisionClient\` adapter before it can enter the OCR run.
- Real model numbers remain not measured until an owner runs the real path after reviewing \`--estimate\`.
- The synthetic fixture covers clean Latin/digit document layouts only. It does not measure Japanese OCR, handwriting, skew, stamps, scans, photos, or multi-page splitting.`,
    verificationResults: `| Model | Provider | Provenance | Measured at | CER | WER | Field accuracy | Note |
| ----- | -------- | ---------- | ----------- | --- | --- | -------------- | ---- |
${resultRows(result)}`,
    analysis:
      "Rows with `measured` provenance can be compared on OCR quality. Rows with `out-of-scope` provenance are integration coverage gaps, not OCR failures, because they were never sent through the image path.",
    reproductionSteps: `\`\`\`sh
cd packages/tech
npm install

npm run ocr:fixture
npm run ocr:estimate
npm run ocr:real
\`\`\``,
    reproductionCost:
      "`ocr:fixture` is keyless and costless. `ocr:estimate` previews the owner-gated real path. `ocr:real` calls configured vision-capable providers and incurs provider token/image charges.",
    cleanup:
      "The OCR fixture and real paths create no external cloud resources. They render local report/data artifacts; review those files before committing.",
    verificationData: `**Dataset.** ${result.dataset.dataset.name} (\`${result.dataset.dataset.id}\`), manifest version ${result.dataset.dataset.manifestVersion}. Source: ${result.dataset.dataset.source}. License: ${sentence(result.dataset.dataset.license)} ${sentence(result.dataset.dataset.imageDistribution)}

**Preprocessing.** Images are rendered as ${result.dataset.preprocessing.mimeType} at ${result.dataset.preprocessing.resolution.widthPx}×${result.dataset.preprocessing.resolution.heightPx}px, ${result.dataset.preprocessing.resolution.dpi} DPI. ${result.dataset.preprocessing.pageSplitting} ${result.dataset.preprocessing.rendering}

**Language and layout.** ${result.dataset.preprocessing.languageScript} ${result.dataset.preprocessing.layoutDifficulty}

**Scoring.** ${sentence(result.dataset.normalization.scoring)} Normalization: ${sentence(result.dataset.normalization.whitespace)} ${sentence(result.dataset.normalization.punctuation)}

**Manifest sample**

| Document id | License | Reference characters | Structured fields |
| ----------- | ------- | -------------------- | ----------------- |
${documentRows(result)}

**Rendered image provenance**

| Document id | Image provenance |
| ----------- | ---------------- |
${renderedImageRows(result)}

Generated: ${result.generatedAt}`,
  });
