#!/bin/sh
# Publish finished research result pages to the corporate site (qmu-co-jp).
#
# Copies docs/research-reports/<slug>.md to <qmu-co-jp>/docs/research/<slug>.md,
# where the Astro "docs" collection renders it at /research/<slug>. The corporate
# site reads plain Markdown with `description` (and optional `title`) frontmatter,
# so this is a one-directional file copy — not a shared framework.
#
# Usage:
#   publish-research.sh [options] [<slug>...]
#
# Options:
#   --all             Publish every report under docs/research-reports/.
#   --qmu-dir DIR     Path to the qmu-co-jp checkout (default: ../qmu-co-jp,
#                     overridable with the QMU_DIR environment variable).
#   --force           Overwrite a destination page even if it was not previously
#                     published by this script.
#   --dry-run         Print what would be copied without writing.
#   -h, --help        Show this help.

set -eu

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
SRC_DIR="$REPO_ROOT/docs/research-reports"
QMU_DIR="${QMU_DIR:-$REPO_ROOT/../qmu-co-jp}"
MARKER="Generated by qmu/research scripts/publish-research.sh"

ALL=0
FORCE=0
DRY=0
SLUGS=""

usage() {
  sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
  case "$1" in
    --all) ALL=1 ;;
    --force) FORCE=1 ;;
    --dry-run) DRY=1 ;;
    --qmu-dir) shift; QMU_DIR="$1" ;;
    -h | --help) usage; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; exit 1 ;;
    *) SLUGS="$SLUGS ${1%.md}" ;;
  esac
  shift
done

QMU_DIR=$(cd "$QMU_DIR" 2>/dev/null && pwd || true)
if [ -z "$QMU_DIR" ] || [ ! -d "$QMU_DIR/docs" ]; then
  echo "Error: qmu-co-jp checkout not found (looked for <dir>/docs)." >&2
  echo "Pass --qmu-dir DIR or set QMU_DIR." >&2
  exit 1
fi

DEST_DIR="$QMU_DIR/docs/research"
LANDING="$QMU_DIR/docs/research.md"

# A source page is publishable only if it begins with a frontmatter block that
# carries a non-empty `description` (required by the corporate site's schema).
has_description() {
  head -n1 "$1" | grep -q '^---[[:space:]]*$' || return 1
  awk '
    NR == 1 { next }
    /^---[[:space:]]*$/ { exit ok ? 0 : 1 }
    /^description:[[:space:]]*[^[:space:]]/ { ok = 1 }
    END { exit ok ? 0 : 1 }
  ' "$1"
}

if [ "$ALL" -eq 1 ]; then
  for f in "$SRC_DIR"/*.md; do
    [ -f "$f" ] || continue
    name=$(basename "$f" .md)
    # README.md (editor doc) and index.md (preview-site landing) are not reports.
    case "$name" in
      README | index) continue ;;
    esac
    SLUGS="$SLUGS $name"
  done
fi

if [ -z "$(echo "$SLUGS" | tr -d ' ')" ]; then
  echo "No reports to publish. Pass a slug or --all." >&2
  exit 0
fi

# Create the section landing once, so /research has an index page.
ensure_landing() {
  [ -f "$LANDING" ] && return 0
  if [ "$DRY" -eq 1 ]; then
    echo "would create section landing: $LANDING"
    return 0
  fi
  cat > "$LANDING" <<'EOF'
---
description: qmuが公開する再現可能な基礎調査の一覧です。各ページに再現手順を記載しています。
---

# 基礎調査

qmuが公開する、再現可能な基礎調査の成果です。各ページは計測した内容・方法・
再現手順を記載しています。ソースコードは公開リポジトリ qmu/research にあります。
EOF
  echo "created section landing: $LANDING"
}

published=0
for slug in $SLUGS; do
  SRC="$SRC_DIR/$slug.md"
  DEST="$DEST_DIR/$slug.md"

  if [ ! -f "$SRC" ]; then
    echo "Error: report not found: docs/research-reports/$slug.md" >&2
    exit 1
  fi
  if ! has_description "$SRC"; then
    echo "Error: $slug.md needs frontmatter with a non-empty description." >&2
    exit 1
  fi
  if [ -f "$DEST" ] && [ "$FORCE" -eq 0 ] && ! grep -q "$MARKER" "$DEST"; then
    echo "Error: $DEST already exists and was not published by this script." >&2
    echo "Use --force to overwrite." >&2
    exit 1
  fi

  if [ "$DRY" -eq 1 ]; then
    echo "would publish: $slug.md -> $DEST"
    continue
  fi

  ensure_landing
  mkdir -p "$DEST_DIR"
  # Copy the page and stamp a provenance marker after the frontmatter so the
  # source of truth (this repo) is clear to anyone reading the corporate site.
  awk -v marker="<!-- $MARKER. Edit the source in qmu/research, not here. -->" '
    /^---[[:space:]]*$/ {
      n++; print
      if (n == 2) { print ""; print marker }
      next
    }
    { print }
  ' "$SRC" > "$DEST"
  echo "published: $slug.md -> docs/research/$slug.md"
  published=$((published + 1))
done

if [ "$DRY" -eq 0 ]; then
  echo "Done. $published page(s) published to $QMU_DIR/docs/research/."
  echo "Review and commit the changes in the qmu-co-jp repository to deploy."
fi
